services:
  client:
    container_name: client
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11558849/clipper-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - VITE_COGNITO_AUTHORITY=${COGNITO_AUTHORITY}
      - VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - VITE_COGNITO_REDIRECT_URI=${COGNITO_REDIRECT_URI}
      - VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
      - VITE_API_URL=${API_URL}

  server:
    container_name: server
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11558849/clipper-server:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
