services:
  client:
    build:
      context: .
      dockerfile: infra/docker/client.Dockerfile
      args:
        VITE_COGNITO_AUTHORITY: ${VITE_COGNITO_AUTHORITY}
        VITE_COGNITO_CLIENT_ID: ${VITE_COGNITO_CLIENT_ID}
        VITE_COGNITO_REDIRECT_URI: ${VITE_COGNITO_REDIRECT_URI}
        VITE_COGNITO_DOMAIN: ${VITE_COGNITO_DOMAIN}
        VITE_API_URL: ${VITE_API_URL}
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    env_file:
      - .env

  server:
    container_name: server
    build:
      context: .
      dockerfile: infra/docker/server.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
