services:
  client:
    container_name: client
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/group83/client:latest
    ports:
      - "5173:5173"
    depends_on:
      - server
    env_file:
      - .env

  server:
    container_name: server
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/group83/server:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
